config/routes.rb
Rails.application.routes.draw do
  
resources :pens

resources :notebook

resources :home
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/notebook.rb
class Notebook < Product
end

app/models/pen.rb
class Pen < Product
end

app/models/product.rb
class Product < ApplicationRecord

  validates :name,:description, :price, :status,   presence: true
  validates :price, numericality: true

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController


  def index
    @products = Product.all
  end




end

app/controllers/pens_controller.rb
class PensController < ApplicationController


  

  def new
  	@pen = Pen.new
  end

  def create
    @pen = Pen.new(pen_params)

    respond_to do |format|
      if @pen.save
        format.html { redirect_to home_index_path, notice: 'Pen was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

   private
   

    # Never trust parameters from the scary internet, only allow the white list through.
    def pen_params
      params.require(:pen).permit(:name, :price, :color, :status, :inward_date, :description)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/home/index.html.erb
<div class="page-header">
  <h1>Listing Products</h1>
</div>

<p id="notice"><%= notice %></p>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Color</th>
      <th>Status</th>
      <th>Inward Date</th>
      <th>Description</th>
    </tr>
  </thead>

  <tbody>
     <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.price %></td>
        <td><%= product.color %></td>
        <td><%= product.status ? "Enabled" : "Disabled" %></td>
        <td><%= product.inward_date%></td>
        <td><%= product.description %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pen', new_pen_path %> | <%= link_to 'New Notebook', new_notebook_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Store</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="main-container" class="container">
      <div class="row">
        
        <div id="content" class="col-md-12">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/pens/_form.html.erb
<%= form_for(@pen) do |f| %>
  <% if @pen.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pen.errors.count, "error") %> prohibited this pen from being saved:</h2>

      <ul>
      <% @pen.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :color %><br>
    <%= f.text_field :color %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.check_box :status %>
  </div>
  <div class="field">
    <%= f.label :inward_date %><br>
    <%= f.text_field :inward_date %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pens/index.html.erb
<div class="page-header">
  <h1>Listing Products</h1>
</div>

<p id="notice"><%= notice %></p>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Color</th>
      <th>Status</th>
      <th>Inward Date</th>
      <th>Description</th>
    </tr>
  </thead>

  <tbody>
     <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.price %></td>
        <td><%= product.color %></td>
        <td><%= product.status ? "Enabled" : "Disabled" %></td>
        <td><%= product.inward_date%></td>
        <td><%= product.description %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/pens/new.html.erb
<div class="page-header">
  <h1>New Pen</h1>
</div>

<%= render 'form' %>

<%= link_to 'Back', home_index_path %>